//
// EvoLudo Project
//
// Copyright 2010-2025 Christoph Hauert
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// For publications in any form, you are kindly requested to attribute the
// author and project as follows:
//
//	Hauert, Christoph (<year>) EvoLudo Project, https://www.evoludo.org
//			(doi: 10.5281/zenodo.14591549 [, <version>])
//
//	<year>:    year of release (or download), and
//	<version>: optional version number (as reported in output header
//			or GUI console) to simplify replication of reported results.
//
// The formatting may be adjusted to comply with publisher requirements.
//

package org.evoludo.simulator;

import java.util.Date;

import org.evoludo.util.Plist;

/**
 * Encapsulates encoding and restoration of EvoLudo engine state, including
 * version handling.
 */
public class StateEncoder {

	private final EvoLudo engine;

	public StateEncoder(EvoLudo engine) {
		this.engine = engine;
	}

	/**
	 * Return version string of current model. Version must include reference to git
	 * commit to ensure reproducibility of results.
	 *
	 * @return the version string
	 */
	public String getVersion() {
		String git = engine.getGit();
		if ("unknown".equals(git))
			return EvoLudo.COPYRIGHT;
		return "EvoLudo: " + git + " " + EvoLudo.COPYRIGHT;
	}

	/**
	 * Encode current state of EvoLudo model as XML string (plist format).
	 *
	 * @return encoded state
	 */
	public String encodeState() {
		StringBuilder plist = new StringBuilder("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
				+ "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n"
				+ "<plist version=\"1.0\">\n" + "<dict>\n");
		plist.append(Plist.encodeKey("Export date", new Date().toString()));
		plist.append(Plist.encodeKey("Title", engine.activeModule.getTitle()));
		plist.append(Plist.encodeKey("Version", getVersion()));
		String java = engine.getJavaVersion();
		if (java != null)
			plist.append(Plist.encodeKey("JavaVersion", java));
		String clo = engine.cloController.getParserCLO();
		clo = clo.replaceAll("--run *", "");
		plist.append(Plist.encodeKey("CLO", clo));
		engine.activeModel.encodeState(plist);
		// the mersenne twister state is pretty long (and uninteresting) keep at end
		plist.append("<key>RNG state</key>\n" + "<dict>\n" + (engine.rng.getRNG().encodeState()) + "</dict>\n");
		plist.append("</dict>\n" + "</plist>");
		return plist.toString();
	}

	/**
	 * Restore state of EvoLudo model from pre-processed plist, which encodes engine
	 * state (see {@link #encodeState()}).
	 * <p>
	 * <strong>Note:</strong> the appropriate model must already have been loaded
	 * and the command line arguments specified with the key <code>CLO</code> in the
	 * <code>plist</code> must also have been processed already.
	 * </p>
	 * <p>
	 * In JRE the options in <code>plist</code> are merged with any other command
	 * line arguments (albeit the ones in <code>plist</code> have priority to
	 * minimize the chance of complications). In GWT
	 * <code>restoreState(Plist)</code> is overridden to first deal with the command
	 * line arguments.
	 * </p>
	 *
	 * @param plist the lookup table with key value pairs
	 * @return {@code true} on successfully restoring state
	 */
	public boolean restoreState(Plist plist) {
		if (plist == null) {
			engine.logger.severe("restore state failed (state empty).");
			return false;
		}
		// retrieve version
		String version = (String) plist.get("Version");
		if (version == null) {
			engine.logger.severe("restore state failed (version missing).");
			return false;
		}
		// version check
		int versionstart = version.indexOf(' ') + 1;
		String restoreGit = version.substring(versionstart, version.indexOf(' ', versionstart));
		String myVersion = getVersion();
		versionstart = myVersion.indexOf(' ') + 1;
		String myGit = myVersion.substring(versionstart, myVersion.indexOf(' ', versionstart));
		if (!myGit.equals(restoreGit))
			// versions differ - may or may not be a problem...
			// note: dirty states always count as being different
			engine.logger.warning("state generated by version " + restoreGit + " but this is " + myGit
					+ " - proceed with caution.");

		// restore RNG generator, population structure and state
		Plist rngstate = (Plist) plist.get("RNG state");
		boolean success = true;
		if (!engine.rng.getRNG().restoreState(rngstate)) {
			engine.logger.warning("restore RNG failed.");
			success = false;
		}
		success &= engine.activeModel.restoreState(plist);
		if (success) {
			engine.logger.info("Restore succeeded.");
			engine.fireModuleRestored();
		} else {
			engine.logger.warning("restore failed - resetting model.");
			engine.modelReset();
		}
		return success;
	}
}
